# Generated by Django 2.2 on 2019-04-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nickname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.TextField(verbose_name='About Me')),
                ('experience', models.TextField(verbose_name='Experience Description')),
                ('education', models.TextField(verbose_name='Education Description')),
            ],
        ),
    ]
