# Generated by Django 2.2 on 2019-04-08 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceBlurb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blurb_text', models.CharField(max_length=200, verbose_name='Experience Text')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, upload_to='images/thumbnails/')),
                ('cover_image', models.ImageField(blank=True, upload_to='images/cover/')),
                ('location', models.CharField(max_length=200, verbose_name='Where did you work')),
                ('title', models.CharField(max_length=200, verbose_name='Job title')),
                ('date', models.CharField(max_length=200, null=True, verbose_name='Date Range')),
                ('short_description', models.TextField(blank=True, verbose_name='Short Description')),
                ('complete_description', models.TextField(blank=True, verbose_name='Complete Description')),
            ],
        ),
        migrations.CreateModel(
            name='Nickname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.TextField(verbose_name='About Me')),
                ('experience', models.TextField(verbose_name='Experience Description')),
                ('education', models.TextField(verbose_name='Education Description')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, upload_to='images/thumbnails/')),
                ('name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('has_source', models.BooleanField(default=True, verbose_name='Has Source Code?')),
                ('source_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Source Code URL')),
                ('short_description', models.TextField(blank=True, verbose_name='Short Description')),
                ('complete_description', models.TextField(blank=True, verbose_name='Complete Description')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/photos/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.ProjectCategory'),
        ),
    ]
