# Generated by Django 2.2 on 2019-04-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='images/thumbnails/')),
                ('cover_image', models.ImageField(upload_to='images/cover/')),
                ('location', models.CharField(max_length=200, verbose_name='Where did you work')),
                ('title', models.CharField(max_length=200, verbose_name='Job title')),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('complete_description', models.TextField(verbose_name='Complete Description')),
            ],
        ),
    ]
