# Generated by Django 2.2 on 2019-04-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_link_text',
            field=models.CharField(default='Github', max_length=200),
        ),
    ]
