# Generated by Django 2.2 on 2019-04-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_project_source_link_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date',
        ),
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.DateField(help_text='Leave empty if still working', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Start Date'),
        ),
    ]
