# Generated by Django 2.2 on 2019-04-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20190410_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave empty if still working', null=True, verbose_name='End Date'),
        ),
    ]
