# Generated by Django 2.2 on 2019-04-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20190410_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, upload_to='images/thumbnails/')),
                ('institution', models.CharField(max_length=200)),
                ('earned', models.CharField(help_text='Diploma, Degree, Certification, etc.', max_length=200, verbose_name='What did you earn')),
                ('date_recieved', models.DateField(help_text='Put expected date if not yet recieved', verbose_name='Date Recieved')),
            ],
        ),
    ]
